# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='complete',
        ),
    ]
