# Generated by Django 3.2.9 on 2021-11-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20211105_1216'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='todo_app_ta_title_186313_idx'),
        ),
    ]
