# Generated by Django 3.2.9 on 2021-11-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_todo_app_ta_title_186313_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='todo_app_ta_title_186313_idx',
        ),
    ]
